### ISSUE TITLE
Dependency graph?

### ISSUE THREAD

**Issue by jmatsushita** [holepunchto/corestore#8]
Hi there,

Just saw you're removing the dependency graph, can I ask what the reason is and if you have plans to maybe provide this functionality as a separate module? I quite liked the abstraction!

Cheers,

Jun

**Comment by andrewosh** [comment]
Hey @jmatsushita,

Yeah that's definitely worth explaining -- sorry for not making it clear why we're making that change. The module's still quite in flux.

When we originally came up with the dependency graph, the thinking was that the graph search would happen outside of any hot path, and therefore wouldn't affect hypercore get/update performance. As we iterated more on hypercore features, it became clear that recent additions we made to the `update` method (namely the `ifAvailable` flag, which attempts to update the hypercore as much as possible from currently-connected peers) were putting the dependency graph search into a hot path. 

With the dep graph, `update({ ifAvailable: true })` needs to wait until the graph traversal completes, so that we know that the core has connected to all possible peers. This turned out to be a significant performance regression, and it wasn't clear how any form of optimization would improve the situation, especially for deeper dependency graphs. We could use a data structure that's designed for graphs instead of hypertrie, but even in that scenario the perf overhead would be too high -- those `update`s need to complete quickly!

We've decided instead to shift towards a bloom filter exchange instead, where we maintain a filter for each peer such that we can quickly test if a peer has a given core. False positives in this case are acceptable (they'll just lead to unnecessary channels being opened, but no data leakage), so we figure that's our best bet.

Hope that clears things up! I'll update this issue when the bloom filter approach is implemented.
